### PR TITLE
Adds Schedule section

### PR DESCRIPTION
**Pull request by stream7**
The ics export is a bit problematic and thus I haven't added a link.
I think it would work if the times in the YAML file are in UTC or if some adjustment is applied afterwards or if a timezone is applied to the calendar? Anyone here knows more about this?

### CODE REVIEW

**Comment by fotos** [comment]
I added most of the comments about this in #32. :disappointed: 

Will try to see what's wrong with the ICS part in the evening.

**Comment by fotos** [comment]
@stream7 ha! Thanks for poking fun at me!

I'm merging this and we 'll take it from here. Will remove the navbar element for now until we have finalised the schedule. Thanks for this. I 'll also give you push access to the site repo so you can fix (or break) stuff directly.

**Comment by fotos** [comment]
@stream7 merged, you can [check it out here](http://euruko2013.org/schedule). I updated the schedule and made various (minor) fixes.

I also fixed the ICS errors and you [can find it here](http://euruko2013.org/schedule.ics). Unfortunately I can't import the calendar into iCal. No idea why.

Furthermore there is a JSON endpoint, consumed by the mobile applications and generated by the same dataset, [here](http://euruko2013.org/schedule.json).

**Comment by stream7** [comment]
@fotos thanks! :smile: 

Regarding the ICS, you have to make to make sure that the file has no white space in the beginning in order to work properly. Now it has a few blank lines.

**Comment by stream7** [comment]
fixed with db6fa99715a92ef6878bb65e3c7625035ecf277e

**Comment by damphyr** [comment]
Hmm, switch Noria and Klabnik around please. Steve is coming Thursday evening and he might be jet-lagged.
Anyway, not important because I have to shuffle the others around as well.

**Comment by fotos** [comment]
@damphyr the order is totally random, just a showoff. The link is not public yet. When we make up our minds we will update the schedule and fill-in the slots.

**Pull request merged**
