### PR TITLE
Replaced ustream embed with a link to channel which has the video archives

### PR DESCRIPTION
**Pull request by eirc**

### CODE REVIEW

**Comment by eirc** [comment]
Should I close this pull request? The embed object right now does link to the ustream channel, it even plays the last video.

**Comment by nikosd** [comment]
Nope, give us some time - we are known slackers :D

**Comment by fotos** [comment]
I'll merge this now and make some final changes on the website.

**Comment by eirc** [comment]
I thought you just ignored it coz the embed works "nicely". As you please then.

**Comment by fotos** [comment]
Did something similar to this merge. Thanks for this! :smile:

**Pull request closed without merging**
