### PR TITLE
Using bootstrap

### PR DESCRIPTION
**Pull request by graffic**
Working with the top navigation bar and the blog, it felt that a grid system and some basic widgets may be useful to speed up development.

The proposals site is using bootstrap, so here is the suggestion to introduce bootstrap.

Benefits:
- Responsive grid system: better than adding responsibe behavior for every widget in every page (quite a lot of work).
- Basic widgets like navigation, buttons, pagination, ...

Note: colors fonts and stuff can be overridden easily when using bootstrap-sass.

I'm working in a branch with bootstrap and the navigation bar behaves much better.

Therefore I leave here the question: do you want bootstrap? I do :)

### CODE REVIEW

**Comment by graffic** [comment]
One thing I've noticed is that is difficult keeping up rebasing my branch, so I will do my best to request a merge today.

**Comment by graffic** [comment]
Arf! Added the pull-request.

Because I'm a bit newbie here, I'll add what I did just in case.
- clone the euruko2013/site repo
- create a local branch in that repo
- add my personal remote (graffic/site)
- pull and set the upstream for the local branch: git pull -u graffic bootstrap
- Now hub worked with: hub pull-request -i 44

Doing the hub pull-request from my repo didn't worked :/

**Comment by fotos** [comment]
I really want to merge this now I've seen the work you put into it!

It will solve many problems with the custom layout and help us develop (standalone) pages more easily. There are a couple of things that this branch breaks (especially when you view it under the mobile viewport) which will have to be resolved first.

Unfortunately I had to merge / do some stuff that were urgent before this branch could be merged and we'll have to resolve a couple of conflicts. I will finish the (standalone) sponsors page as well, which is really important, and then work on porting everything that changed in between to bootstrap and finally merge this.

Sound like a plan?

**Comment by fotos** [comment]
In the mean time... @graffic if you can rebase this again it would be a huge service!

**Comment by graffic** [comment]
Of course I can rebase it. I'll be working on this in the evening.

The plan is:
- rebase.
- fix the problems you talked about if I'm able to see them too. @fotos If you have some minutes... tell me what you didn't like in the branch and I'll fix it.

**Comment by graffic** [comment]
Rebased.

Let me do an UI check.

**Comment by graffic** [comment]
Fixed the homepage background problem and added font-awesome.

**Comment by graffic** [comment]
And the last change I believe for today is the margins when resizing the homepage.

**Comment by tsironis** [comment]
Hey, guys. I was wondering when you'll merge this pull request, in order to add the atom feed icon.

**Pull request merged**
