### PR TITLE
Adds individual speaker pages

### PR DESCRIPTION
**Pull request by avgerin0s**
This pull request refers to #31 

The things I did.
- Added /speakers directory
- Added /speakers/speaker.html.erb template for individual pages

Adds individual pages for every speaker dynamically according to data/speakers.yml under the /speakers/<%= speaker.short_name %> url and  **lorem ipsum** bio data.

Also adds a link to those individual pages in the /speakers for every speaker.

Still needs real data for bio though

@fotos Any ideas?

### CODE REVIEW

**Comment by avgerin0s** [comment]
Merge me please :gem:

**Comment by graffic** [comment]
Merged, please pull and if you find any problem tell me or fix it :P

**Comment by avgerin0s** [comment]
Everything works fine! Except content which is lorem ipsum. Check data/speakers.yml for more info.

**Comment by avgerin0s** [comment]
Also a link to /speakers must be added but I didn't know where it would fit.

**Pull request merged**
