### PR TITLE
adds tags and latest posts link to single post view

### PR DESCRIPTION
**Pull request by stream7**
partially fix for #38

### CODE REVIEW

**Comment by graffic** [comment]
@webspirit Is working on this :/

Perhaps she can shed some extra light on her work about this.

**Comment by graffic** [comment]
I did review the patch and I found that the aside pushes the comments down. I mean, the disqus comments start after the aside finishes.

I believe comments should start after the post.

Something like 

``` html
            <div class="span6">
              <header>
                <h2 itemprop="headline"><%= current_page.title %></h2>
              </header>
              <section class="body" itemprop="text">
                <%= yield %>
              </section>
              <%= partial 'blog/disqus' %>
            </div>
```

What do you think?

**Comment by stream7** [comment]
Hi @graffic !
You are right.
I think this last commit fixes that. Please have a look.

**Comment by graffic** [comment]
That last change does strange things.



As far as I understood you want to have:
1. First row:
   - Title
2. Second row
   - Content
   - Authors + Sidebar

Perhaps something like this could help:

``` html
<div clas="row">
    <whatever class="span8 offset2">title</whatever>
</div>
<div clas="row">
    <whatever class="span6 offset2">Content + Disqus</whatever>
    <whatever class="span2">Authors + Sidebar</whatever>
</div>
```

Or nested

``` html
<div clas="row">
    <whatever class="span8 offset2">title</whatever>
    <div clas="row">
        <whatever class="span6">Content + Disqus</whatever>
        <whatever class="span2">Authors + Sidebar</whatever>
    </div>
</div>
```

**Comment by stream7** [comment]
Yes, I didn't realize there could be more than one authors.
I did it like you said. The only "problem" now is that the authors appear after the comments in mobile view.

**Comment by graffic** [comment]
You're right about authors in mobile.

Ideas:
- Leave it as it is.
- Include just a small reference about the authors visible only in mobile designs (and hide the big photos).
- Float authors inside the post contents.

Or perhaps someone from the skroutz team can help us with any tricks they use in their amazing responsive design.

**Pull request merged**
